#!/usr/bin/env bash

set -e
set -o pipefail
set -x

UPDATE_MODE=${UPDATE_MODE:-squash}

SCRIPT_NAME=$(basename $0)

case $UPDATE_MODE in
squash)
  echo "$SCRIPT_NAME: executed with [UPDATE_MODE=$UPDATE_MODE]"
  ;;
*)
  echo "$SCRIPT_NAME: skipping because invalid UPDATE_MODE value. Accepted values are 'squash'"
  exit 1
  ;;
esac

if [[ -z $GITHUB_TOKEN ]]; then
  echo "$SCRIPT_NAME: skipping because GITHUB_TOKEN env. variable is not set"
  exit 1
fi

git config user.email "slicerbot@slicer.org"
git config user.name "Slicer Bot"

pushURL=https://$GITHUB_TOKEN@github.com/Slicer/apidocs.slicer.org
git config --add remote.origin.pushURL $pushURL
echo "$SCRIPT_NAME: added 'remote.origin.pushURL' with GITHUB_TOKEN"

TARGET_BRANCH=gh-pages

if [[ $UPDATE_MODE == "squash" ]]; then
  git fetch origin $TARGET_BRANCH
  git branch -D $TARGET_BRANCH || true
  git checkout -b $TARGET_BRANCH FETCH_HEAD
  first_commit=$(git rev-list --max-parents=0 HEAD)
  git reset --soft $first_commit
  git commit --amend -m "Slicer apidocs squashed

It was automatically generated by the script ``$SCRIPT_NAME`` [1]

[1] https://github.com/Slicer/apidocs.slicer.org/blob/main/$SCRIPT_NAME
"
  git push origin $TARGET_BRANCH --force
  push_exit_code=$?

else
  echo "$SCRIPT_NAME: skipping because invalid UPDATE_MODE [$UPDATE_MODE]"
  exit 1
fi


if [[ ! $push_exit_code -eq 0 ]]; then
  echo "$SCRIPT_NAME: skipping because push command failed"
  exit $push_exit_code
fi

echo "$SCRIPT_NAME: $TARGET_BRANCH successfully $UPDATE_MODE"
